### ISSUE TITLE
None of these files exist:   * close.png

### ISSUE THREAD

**Issue by ajiehatajie** [WayneKim92/react-native-good-tooltip#15]
Error: Unable to resolve module ../assets/close.png apps/node_modules/react-native-good-tooltip/lib/commonjs/index.js:

None of these files exist:
  * close.png

**Comment by Wayne-Kim** [comment]
Thank you for posting the issue.

Can you check it out in the RN project in the example folder of this repo?

**Comment by Wayne-Kim** [comment]
The problem occurred because the assets were not included in the dist folder.

A modified version v1.2.1 has been distributed.

Thank you for sharing the issue.
